from __future__ import annotations

from collections import defaultdict
from html import escape
from pathlib import Path
import shutil
import textwrap
from typing import Any, Callable

from .models import SermonRecord
from .scripture_index import (
    ScriptureEntry,
    build_scripture_index,
    frequent_scripture_entries,
    scripture_entry_totals,
    scripture_flag,
    scripture_role,
)
from .util import page_stem, slugify, write_text


def write_html_site(records: list[SermonRecord], site_dir: Path, config: dict[str, Any]) -> dict[str, Any]:
    """Write a private static HTML site that opens directly in a browser."""
    if site_dir.exists():
        shutil.rmtree(site_dir)
    for child in ("assets", "sermons", "series", "speakers", "scripture", "themes", "review"):
        (site_dir / child).mkdir(parents=True, exist_ok=True)

    sorted_records = sorted(records, key=lambda record: (record.date or "9999-99-99", record.title.casefold()))
    sermon_paths = unique_sermon_paths(sorted_records)
    context = SiteContext(records=sorted_records, sermon_paths=sermon_paths)

    write_assets(site_dir)
    write_text(site_dir / "index.html", home_page(context, config))
    write_text(site_dir / "review" / "index.html", review_page(context, config))
    for record in sorted_records:
        write_text(site_dir / "sermons" / sermon_paths[record_key(record)], sermon_page(record, context, config))

    write_group_pages(site_dir, context, "series", "Series", lambda record: [record.series] if record.series else [])
    write_group_pages(site_dir, context, "speakers", "Speakers", lambda record: [record.speaker] if record.speaker else [])
    write_scripture_pages(site_dir, context)
    write_group_pages(site_dir, context, "themes", "Themes", lambda record: [*record.topics, *record.themes])
    return {"site_dir": str(site_dir), "index_path": str((site_dir / "index.html").resolve()), "sermon_count": len(records)}


class SiteContext:
    def __init__(self, records: list[SermonRecord], sermon_paths: dict[str, str]) -> None:
        self.records = records
        self.sermon_paths = sermon_paths
        self.records_by_title = {record.title.casefold(): record for record in records}
        self.records_by_page_stem = {" ".join(part for part in (record.date, record.title) if part).casefold(): record for record in records}
        self.records_by_page_stem.update({page_stem_for_related(record).casefold(): record for record in records})

    def sermon_href(self, record: SermonRecord, depth: int = 0) -> str:
        return prefix(depth) + "sermons/" + self.sermon_paths[record_key(record)]

    def entity_href(self, kind: str, name: str, depth: int = 0) -> str:
        return prefix(depth) + kind + "/" + entity_filename(name)

    def related_sermon(self, name: str) -> SermonRecord | None:
        key = name.casefold()
        if key in self.records_by_title:
            return self.records_by_title[key]
        if key in self.records_by_page_stem:
            return self.records_by_page_stem[key]
        return self.records_by_page_stem.get(key.replace(" - ", " "))


def unique_sermon_paths(records: list[SermonRecord]) -> dict[str, str]:
    paths: dict[str, str] = {}
    seen: dict[str, int] = {}
    for record in records:
        base = slugify(" ".join(part for part in (record.date, record.title) if part))
        count = seen.get(base, 0)
        seen[base] = count + 1
        filename = f"{base}.html" if count == 0 else f"{base}-{count + 1}.html"
        paths[record_key(record)] = filename
    return paths


def home_page(context: SiteContext, config: dict[str, Any]) -> str:
    records = context.records
    church_name = str(config.get("church", {}).get("name") or "Sermon Archive")
    page_heading = church_name if church_name.casefold().endswith("archive") else f"{church_name} Sermon Archive"
    latest = list(reversed(records[-12:]))
    body = [
        f"<h1>{escape(page_heading)}</h1>",
        '<p class="lede">Private local website generated by <code>sermon-archive-wiki</code>. Nothing here is published by default.</p>',
        stats_grid(records),
        '<section class="panel">',
        "<h2>Find A Sermon</h2>",
        '<input class="search" type="search" data-search-input placeholder="Search title, speaker, series, scripture, or transcript status">',
        sermon_table(records, context, depth=0),
        "</section>",
        '<section class="panel">',
        "<h2>Recent Sermons</h2>",
        sermon_cards(latest, context, depth=0),
        "</section>",
    ]
    return layout("Sermon Archive", "\n".join(body), depth=0, active="home")


def sermon_page(record: SermonRecord, context: SiteContext, config: dict[str, Any]) -> str:
    body: list[str] = [f"<h1>{escape(record.title)}</h1>"]
    body.append('<div class="sermon-layout">')
    body.append('<article class="article">')
    if record.review_flags or record.questionable_claims:
        body.append(callout("Review needed", [*record.review_flags, *record.questionable_claims]))
    body.append("<h2>Summary</h2>")
    if record.generated_summary:
        body.append(callout(summary_callout_title(record), [record.generated_summary], kind="note"))
    else:
        body.append('<p class="muted">No generated summary was created for this sermon.</p>')
    body.append("<h2>Cross-References</h2>")
    body.append(cross_refs(record, context, depth=1))
    body.append("<h2>Transcript</h2>")
    body.append(transcript_html(record, config))
    body.append("</article>")
    body.append(metadata_aside(record, context))
    body.append("</div>")
    return layout(record.title, "\n".join(body), depth=1, active="sermons")


def write_group_pages(
    site_dir: Path,
    context: SiteContext,
    kind: str,
    title: str,
    key_func: Callable[[SermonRecord], list[str]],
) -> None:
    grouped: dict[str, list[SermonRecord]] = defaultdict(list)
    for record in context.records:
        for name in key_func(record):
            if name:
                grouped[name].append(record)

    index_body = [
        f"<h1>{escape(title)}</h1>",
        '<section class="panel">',
        '<input class="search" type="search" data-search-input placeholder="Filter this index">',
        entity_index_table(grouped, kind, title),
    ]
    index_body.append("</section>")
    write_text(site_dir / kind / "index.html", layout(title, "\n".join(index_body), depth=1, active=kind))

    singulars = {"Series": "Series", "Speakers": "Speaker", "Themes": "Theme"}
    singular = singulars.get(title, title[:-1] if title.endswith("s") else title)
    for name, items in grouped.items():
        body = [
            f"<h1>{escape(name)}</h1>",
            f'<p class="lede">{escape(singular)} page generated for private sermon review.</p>',
            sermon_table(sorted(items, key=lambda record: (record.date or "9999-99-99", record.title.casefold())), context, depth=1),
        ]
        write_text(site_dir / kind / entity_filename(name), layout(name, "\n".join(body), depth=1, active=kind))


def write_scripture_pages(site_dir: Path, context: SiteContext) -> None:
    grouped = build_scripture_index(context.records)
    index_body = [
        "<h1>Scripture</h1>",
        '<p class="lede">A private concordance of primary sermon texts and Scripture references found in transcripts.</p>',
        frequent_scripture_panel(grouped),
        '<section class="panel">',
        '<input class="search" type="search" data-search-input placeholder="Filter this index">',
        scripture_index_table(grouped),
        "</section>",
    ]
    write_text(site_dir / "scripture" / "index.html", layout("Scripture", "\n".join(index_body), depth=1, active="scripture"))

    for ref, entries in grouped.items():
        sermons, mentions, primary = scripture_entry_totals(entries)
        body = [
            f"<h1>{escape(ref)}</h1>",
            f'<p class="lede">Referenced in {sermons} sermon{"s" if sermons != 1 else ""} with {mentions} detected mention{"s" if mentions != 1 else ""}. {primary} primary sermon text{"s" if primary != 1 else ""}.</p>',
            '<section class="panel">',
            '<input class="search" type="search" data-search-input placeholder="Filter sermons">',
            scripture_sermon_table(entries, context, depth=1),
            "</section>",
        ]
        write_text(site_dir / "scripture" / entity_filename(ref), layout(ref, "\n".join(body), depth=1, active="scripture"))


def entity_index_table(grouped: dict[str, list[SermonRecord]], kind: str, title: str) -> str:
    labels = {"Series": "Series", "Speakers": "Speaker", "Scripture": "Scripture", "Themes": "Theme"}
    name_label = labels.get(title, title[:-1] if title.endswith("s") else title)
    rows = [
        '<table class="sermon-table sortable-table" data-sortable data-sort-initial="1:desc">',
        "<thead><tr>",
        sortable_header(name_label, help_text=f"{name_label} name. Click the linked name to open its detail page."),
        sortable_header("Sermons", "number", "Number of sermons in this index entry."),
        sortable_header("First", "date", "Earliest sermon date in this index entry."),
        sortable_header("Latest", "date", "Latest sermon date in this index entry."),
        "</tr></thead><tbody>",
    ]
    for name, items in sorted(grouped.items(), key=lambda item: (-len(item[1]), item[0].casefold())):
        dates = sorted(record.date for record in items if record.date)
        first_date = dates[0] if dates else ""
        latest_date = dates[-1] if dates else ""
        count = len(items)
        href = entity_filename(name)
        rows.append(
            f'<tr data-search-row data-search="{search_blob([name, count, first_date, latest_date])}">'
            f'<td data-sort-value="{sort_attr(name)}"><a href="{href}">{escape(name)}</a></td>'
            f'<td data-sort-value="{count}">{count}</td>'
            f'<td data-sort-value="{escape(first_date, quote=True)}">{escape(first_date or "?")}</td>'
            f'<td data-sort-value="{escape(latest_date, quote=True)}">{escape(latest_date or "?")}</td>'
            "</tr>"
        )
    rows.append("</tbody></table>")
    return "\n".join(rows)


def scripture_index_table(grouped: dict[str, list[ScriptureEntry]]) -> str:
    rows = [
        '<table class="sermon-table sortable-table" data-sortable data-sort-initial="2:desc">',
        "<thead><tr>",
        sortable_header("Scripture", help_text="Bible book or passage. Click the linked reference to see matching sermons."),
        sortable_header(
            "Sermons",
            "number",
            "Number of sermon pages where this book or passage appears as a primary text or transcript reference.",
        ),
        sortable_header(
            "Mentions",
            "number",
            "Total deterministic matches found in sermon titles, metadata, and transcript text. Treat as a review aid, not a pastoral claim.",
        ),
        sortable_header(
            "Primary",
            "number",
            "Number of sermons where this appears to be the main or explicitly listed sermon text.",
        ),
        sortable_header("First", "date", "Earliest sermon date where this reference appears."),
        sortable_header("Latest", "date", "Latest sermon date where this reference appears."),
        "</tr></thead><tbody>",
    ]
    for ref, entries in sorted(grouped.items(), key=lambda item: (-scripture_entry_totals(item[1])[1], item[0].casefold())):
        sermons, mentions, primary = scripture_entry_totals(entries)
        flag = scripture_flag(ref, entries)
        flag_html = flag_badge(flag) if flag else ""
        dates = sorted(entry.record.date for entry in entries if entry.record.date)
        first_date = dates[0] if dates else ""
        latest_date = dates[-1] if dates else ""
        href = entity_filename(ref)
        rows.append(
            f'<tr data-search-row data-search="{search_blob([ref, sermons, mentions, primary, first_date, latest_date])}">'
            f'<td data-sort-value="{sort_attr(ref)}"><a href="{href}">{escape(ref)}</a>{flag_html}</td>'
            f'<td data-sort-value="{sermons}">{sermons}</td>'
            f'<td data-sort-value="{mentions}">{mentions}</td>'
            f'<td data-sort-value="{primary}">{primary}</td>'
            f'<td data-sort-value="{escape(first_date, quote=True)}">{escape(first_date or "?")}</td>'
            f'<td data-sort-value="{escape(latest_date, quote=True)}">{escape(latest_date or "?")}</td>'
            "</tr>"
        )
    rows.append("</tbody></table>")
    return "\n".join(rows)


def frequent_scripture_panel(grouped: dict[str, list[ScriptureEntry]]) -> str:
    flagged = frequent_scripture_entries(grouped)[:20]
    if not flagged:
        return ""
    rows = [
        '<section class="panel">',
        "<h2>Frequent Specific Passages</h2>",
        '<p class="muted">Specific chapters, verse ranges, or passages that recur enough to deserve pastoral review.</p>',
        '<table class="sermon-table sortable-table" data-sortable data-sort-initial="2:desc">',
        "<thead><tr>",
        sortable_header("Passage", help_text="Specific chapter, verse, or passage range detected more than once."),
        sortable_header("Sermons", "number", "Number of sermon pages where this specific passage appears."),
        sortable_header("Mentions", "number", "Total detected mentions of this specific passage."),
        sortable_header("Flag", help_text="Why the passage is being surfaced for review."),
        "</tr></thead><tbody>",
    ]
    for ref, entries, flag in flagged:
        sermons, mentions, _primary = scripture_entry_totals(entries)
        rows.append(
            f'<tr data-search-row data-search="{search_blob([ref, sermons, mentions, flag])}">'
            f'<td data-sort-value="{sort_attr(ref)}"><a href="{entity_filename(ref)}">{escape(ref)}</a></td>'
            f'<td data-sort-value="{sermons}">{sermons}</td>'
            f'<td data-sort-value="{mentions}">{mentions}</td>'
            f'<td data-sort-value="{sort_attr(flag)}">{flag_badge(flag)}</td>'
            "</tr>"
        )
    rows.extend(["</tbody></table>", "</section>"])
    return "\n".join(rows)


def flag_badge(label: str) -> str:
    return (
        ' <span style="display:inline-block;margin-left:7px;border:1px solid #c7b46b;'
        'background:#fff8d8;color:#5d4b00;border-radius:999px;padding:2px 7px;'
        'font:700 11px/1.4 system-ui,sans-serif;vertical-align:middle">'
        f"{escape(label)}</span>"
    )


def scripture_sermon_table(entries: list[ScriptureEntry], context: SiteContext, depth: int) -> str:
    rows = [
        '<table class="sermon-table sortable-table" data-sortable data-sort-initial="0:desc">',
        "<thead><tr>",
        sortable_header("Date", "date", "Date the sermon was preached or published."),
        sortable_header("Title", help_text="Sermon title. Click to open the generated sermon page."),
        sortable_header("Speaker", help_text="Preacher or speaker associated with the sermon."),
        sortable_header("Series", help_text="Sermon series associated with the sermon."),
        sortable_header("Role", help_text="Primary means this was likely the main sermon text. Referenced means it was detected elsewhere in the transcript."),
        sortable_header("Mentions", "number", "Number of deterministic matches for this reference in this sermon."),
        "</tr></thead><tbody>",
    ]
    for entry in sorted(entries, key=lambda item: (item.record.date or "9999-99-99", item.record.title.casefold())):
        record = entry.record
        role = scripture_role(entry)
        speaker_cell = entity_link("speakers", record.speaker, context, depth) if record.speaker else '<span class="muted">Review</span>'
        series_cell = entity_link("series", record.series, context, depth) if record.series else '<span class="muted">Review</span>'
        rows.append(
            f'<tr data-search-row data-search="{search_blob([record.title, record.date, record.speaker, record.series, role, entry.mentions])}">'
            f'<td data-sort-value="{escape(record.date, quote=True)}">{escape(record.date or "?")}</td>'
            f'<td data-sort-value="{sort_attr(record.title)}"><a href="{context.sermon_href(record, depth)}">{escape(record.title)}</a></td>'
            f'<td data-sort-value="{sort_attr(record.speaker)}">{speaker_cell}</td>'
            f'<td data-sort-value="{sort_attr(record.series)}">{series_cell}</td>'
            f'<td data-sort-value="{sort_attr(role)}">{escape(role)}</td>'
            f'<td data-sort-value="{entry.mentions}">{entry.mentions}</td>'
            "</tr>"
        )
    rows.append("</tbody></table>")
    return "\n".join(rows)


def review_page(context: SiteContext, config: dict[str, Any]) -> str:
    actionable = [
        record
        for record in context.records
        if record.review_flags or record.questionable_claims or not record.transcript_text.strip() or record.generated_summary
    ]
    body = [
        "<h1>Review Inbox</h1>",
        '<p class="lede">Pages with specific flags, missing transcript text, or AI-generated content.</p>',
        f'<div class="stat-grid"><div class="stat"><strong>{len(actionable)}</strong><span>Actionable</span></div>'
        f'<div class="stat"><strong>{len(context.records)}</strong><span>Total Drafts</span></div></div>',
        '<section class="panel">',
        '<input class="search" type="search" data-search-input placeholder="Filter review items">',
        '<table class="sermon-table sortable-table" data-sortable data-sort-initial="1:desc"><thead><tr>',
        sortable_header("Sermon", help_text="Generated sermon page needing review."),
        sortable_header("Date", "date", "Date the sermon was preached or published."),
        sortable_header("Flags", help_text="Review notes generated during ingest."),
        "</tr></thead><tbody>",
    ]
    for record in actionable:
        flags = [*record.review_flags, *record.questionable_claims]
        if not record.transcript_text.strip():
            flags.append("Missing transcript text")
        if record.generated_summary:
            flags.append("Review generated summary")
        body.append(
            f'<tr data-search-row data-search="{search_blob([record.title, record.date, "; ".join(flags)])}">'
            f'<td data-sort-value="{sort_attr(record.title)}"><a href="{context.sermon_href(record, depth=1)}">{escape(record.title)}</a></td>'
            f'<td data-sort-value="{escape(record.date, quote=True)}">{escape(record.date or "?")}</td>'
            f'<td data-sort-value="{sort_attr("; ".join(flags))}">{escape("; ".join(flags))}</td></tr>'
        )
    body.extend(["</tbody></table>", "</section>"])
    return layout("Review Inbox", "\n".join(body), depth=1, active="review")


def stats_grid(records: list[SermonRecord]) -> str:
    series = {record.series for record in records if record.series}
    speakers = {record.speaker for record in records if record.speaker}
    missing = sum(1 for record in records if not record.transcript_text.strip())
    return (
        '<div class="stat-grid">'
        f'<div class="stat"><strong>{len(records)}</strong><span>Sermons</span></div>'
        f'<div class="stat"><strong>{len(series)}</strong><span>Series</span></div>'
        f'<div class="stat"><strong>{len(speakers)}</strong><span>Speakers</span></div>'
        f'<div class="stat"><strong>{missing}</strong><span>Missing Transcripts</span></div>'
        "</div>"
    )


def sermon_table(records: list[SermonRecord], context: SiteContext, depth: int) -> str:
    rows = [
        '<table class="sermon-table sortable-table" data-sortable data-sort-initial="0:desc">',
        "<thead><tr>",
        sortable_header("Date", "date", "Date the sermon was preached or published."),
        sortable_header("Title", help_text="Sermon title. Click to open the generated sermon page."),
        sortable_header("Speaker", help_text="Preacher or speaker associated with the sermon."),
        sortable_header("Series", help_text="Sermon series associated with the sermon."),
        sortable_header("Transcript", help_text="Whether transcript text was provided, caption-derived, catalog-only, or missing."),
        "</tr></thead><tbody>",
    ]
    for record in records:
        blob = search_blob(
            [record.title, record.date, record.speaker, record.series, " ".join(record.scripture_refs), " ".join(record.mentioned_scripture_refs), record.transcript_status]
        )
        speaker_cell = entity_link("speakers", record.speaker, context, depth) if record.speaker else '<span class="muted">Review</span>'
        series_cell = entity_link("series", record.series, context, depth) if record.series else '<span class="muted">Review</span>'
        rows.append(
            f'<tr data-search-row data-search="{blob}">'
            f'<td data-sort-value="{escape(record.date, quote=True)}">{escape(record.date or "?")}</td>'
            f'<td data-sort-value="{sort_attr(record.title)}"><a href="{context.sermon_href(record, depth)}">{escape(record.title)}</a></td>'
            f'<td data-sort-value="{sort_attr(record.speaker)}">{speaker_cell}</td>'
            f'<td data-sort-value="{sort_attr(record.series)}">{series_cell}</td>'
            f'<td data-sort-value="{sort_attr(record.transcript_status)}">{escape(record.transcript_status)}</td>'
            "</tr>"
        )
    rows.append("</tbody></table>")
    return "\n".join(rows)


def sortable_header(label: str, sort_type: str = "text", help_text: str = "") -> str:
    help_html = info_popup(label, help_text) if help_text else ""
    return (
        f'<th data-sort-type="{escape(sort_type, quote=True)}">'
        '<div class="th-content">'
        f'<button class="sort-button" type="button">{escape(label)}<span class="sort-indicator" aria-hidden="true"></span></button>'
        f"{help_html}"
        "</div>"
        "</th>"
    )


def info_popup(label: str, help_text: str) -> str:
    return (
        '<span class="info-popover" tabindex="0" role="button" '
        f'aria-label="About {escape(label, quote=True)}">'
        '<span class="info-icon" aria-hidden="true">?</span>'
        f'<span class="info-bubble" role="tooltip">{escape(help_text)}</span>'
        "</span>"
    )


def sermon_cards(records: list[SermonRecord], context: SiteContext, depth: int) -> str:
    cards = ['<div class="card-grid">']
    for record in records:
        meta = " | ".join(part for part in (record.date, record.speaker, record.series) if part)
        cards.append(
            f'<a class="card" href="{context.sermon_href(record, depth)}">'
            f"<strong>{escape(record.title)}</strong><span>{escape(meta)}</span></a>"
        )
    cards.append("</div>")
    return "\n".join(cards)


def metadata_aside(record: SermonRecord, context: SiteContext) -> str:
    items = [
        ("Date", escape(record.date or "Review needed")),
        ("Speaker", entity_link("speakers", record.speaker, context, depth=1) if record.speaker else "Review needed"),
        ("Series", entity_link("series", record.series, context, depth=1) if record.series else "Review needed"),
        ("Transcript", escape(record.transcript_status)),
        ("Status", "draft"),
    ]
    if record.scripture_refs:
        refs = ", ".join(entity_link("scripture", ref, context, depth=1) for ref in record.scripture_refs)
        items.insert(3, ("Scripture", refs))
    referenced_refs = [ref for ref in record.mentioned_scripture_refs if ref.casefold() not in {item.casefold() for item in record.scripture_refs}]
    if referenced_refs:
        limited = referenced_refs[:12]
        refs = ", ".join(entity_link("scripture", ref, context, depth=1) for ref in limited)
        if len(referenced_refs) > len(limited):
            refs += f", +{len(referenced_refs) - len(limited)} more"
        insert_at = 4 if record.scripture_refs else 3
        items.insert(insert_at, ("Referenced Scripture", refs))
    html = ['<aside class="infobox"><h2>Sermon Metadata</h2><dl>']
    for label, value in items:
        html.append(f"<dt>{escape(label)}</dt><dd>{value}</dd>")
    html.append("</dl>")
    if record.youtube_url:
        html.append(f'<a class="button" href="{escape(record.youtube_url)}">Open YouTube</a>')
    html.append("<h3>Sources</h3><ul>")
    for source in [*record.source_files, *[audio for audio in record.audio_files if audio not in record.source_files]]:
        html.append(f"<li>{source_link(source)}</li>")
    html.append("</ul></aside>")
    return "\n".join(html)


def cross_refs(record: SermonRecord, context: SiteContext, depth: int) -> str:
    links: list[str] = []
    if record.series:
        links.append(entity_link("series", record.series, context, depth))
    if record.speaker:
        links.append(entity_link("speakers", record.speaker, context, depth))
    links.extend(entity_link("scripture", ref, context, depth) for ref in record.scripture_refs)
    referenced_refs = [ref for ref in record.mentioned_scripture_refs if ref.casefold() not in {item.casefold() for item in record.scripture_refs}]
    links.extend(entity_link("scripture", ref, context, depth) for ref in referenced_refs[:20])
    links.extend(entity_link("themes", theme, context, depth) for theme in [*record.topics, *record.themes])
    for related in record.related_sermons[:8]:
        related_record = context.related_sermon(related)
        if related_record:
            links.append(f'<a href="{context.sermon_href(related_record, depth)}">Related: {escape(related_record.title)}</a>')
    if not links:
        return '<p class="muted">No cross-references found yet.</p>'
    return '<div class="pill-row">' + "".join(f'<span class="pill">{link}</span>' for link in links) + "</div>"


def summary_callout_title(record: SermonRecord) -> str:
    if record.summary_source == "external_command" or "ai" in record.summary_status.casefold():
        return "AI-generated summary; review before relying on it"
    return "Generated summary; review before relying on it"


def page_stem_for_related(record: SermonRecord) -> str:
    return page_stem(record.date, record.title)


def transcript_html(record: SermonRecord, config: dict[str, Any]) -> str:
    if not record.transcript_text.strip():
        return '<p class="muted">No transcript text is available yet.</p>'
    excerpt_chars = int(config.get("output", {}).get("transcript_excerpt_chars") or 0)
    include_full = bool(config.get("output", {}).get("include_full_transcripts", True))
    text = record.transcript_text.strip()
    if excerpt_chars > 0:
        text = text[:excerpt_chars].rstrip() + ("..." if len(record.transcript_text) > excerpt_chars else "")
    elif not include_full:
        text = textwrap.shorten(text.replace("\n", " "), width=1200, placeholder="...")
    paragraphs = [paragraph.strip() for paragraph in text.split("\n\n") if paragraph.strip()]
    return '<div class="transcript">' + "\n".join(f"<p>{escape(paragraph)}</p>" for paragraph in paragraphs) + "</div>"


def callout(title: str, items: list[str], kind: str = "warning") -> str:
    body = "".join(f"<li>{escape(item)}</li>" for item in items if item)
    return f'<div class="callout {kind}"><strong>{escape(title)}</strong><ul>{body}</ul></div>'


def entity_link(kind: str, name: str, context: SiteContext, depth: int) -> str:
    if not name:
        return ""
    return f'<a href="{context.entity_href(kind, name, depth)}">{escape(name)}</a>'


def source_link(source: str) -> str:
    if source.startswith(("http://", "https://")):
        return f'<a href="{escape(source)}">{escape(source)}</a>'
    return f"<code>{escape(source)}</code>"


def layout(title: str, body: str, depth: int, active: str) -> str:
    p = prefix(depth)
    nav_items = [
        ("home", "Home", "index.html"),
        ("series", "Series", "series/index.html"),
        ("speakers", "Speakers", "speakers/index.html"),
        ("scripture", "Scripture", "scripture/index.html"),
        ("themes", "Themes", "themes/index.html"),
        ("review", "Review", "review/index.html"),
    ]
    nav = "\n".join(
        f'<a class="{ "active" if key == active else "" }" href="{p}{href}">{label}</a>'
        for key, label, href in nav_items
    )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(title)} - Sermon Archive Wiki</title>
  <link rel="stylesheet" href="{p}assets/site.css">
</head>
<body>
  <div class="app-shell">
    <aside class="sidebar">
      <a class="brand" href="{p}index.html">Sermon Archive Wiki</a>
      <nav>{nav}</nav>
      <p class="local-note">Private local files. Not published.</p>
    </aside>
    <main class="content">{body}</main>
  </div>
  <script src="{p}assets/site.js"></script>
</body>
</html>
"""


def write_assets(site_dir: Path) -> None:
    write_text(
        site_dir / "assets" / "site.css",
        """*{box-sizing:border-box}body{margin:0;background:#f7f6f1;color:#222;font:16px/1.55 Georgia,"Times New Roman",serif}.app-shell{display:grid;grid-template-columns:260px minmax(0,1fr);min-height:100vh}.sidebar{background:#fdfcf8;border-right:1px solid #d9d4c8;padding:24px;position:sticky;top:0;height:100vh}.brand{display:block;color:#111;font:700 22px/1.1 system-ui,sans-serif;text-decoration:none;margin-bottom:24px}.sidebar nav{display:grid;gap:4px}.sidebar nav a{color:#2d4b73;text-decoration:none;border-radius:6px;padding:8px 10px;font:600 14px/1.2 system-ui,sans-serif}.sidebar nav a:hover,.sidebar nav a.active{background:#e9eef5}.local-note{color:#746f66;font:13px/1.4 system-ui,sans-serif;margin-top:28px}.content{max-width:1180px;padding:36px 44px}h1{font:700 40px/1.12 system-ui,sans-serif;margin:0 0 12px}h2{font:700 24px/1.2 system-ui,sans-serif;margin:32px 0 12px}h3{font:700 16px/1.2 system-ui,sans-serif;margin:24px 0 8px}.lede{font-size:19px;color:#4a4740;max-width:760px}.stat-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:12px;margin:24px 0}.stat{background:#fff;border:1px solid #d9d4c8;border-radius:8px;padding:16px}.stat strong{display:block;font:800 30px/1 system-ui,sans-serif}.stat span{color:#675f54;font:13px/1.3 system-ui,sans-serif;text-transform:uppercase;letter-spacing:.04em}.panel{background:#fff;border:1px solid #d9d4c8;border-radius:8px;padding:18px;margin:22px 0}.search{width:100%;border:1px solid #bbb3a3;border-radius:6px;padding:11px 12px;margin:0 0 14px;font:16px system-ui,sans-serif}.sermon-table{width:100%;border-collapse:collapse;background:#fff}.sermon-table th,.sermon-table td{border-bottom:1px solid #e5e0d6;padding:9px 8px;text-align:left;vertical-align:top}.sermon-table th{font:700 13px system-ui,sans-serif;color:#5e574d;background:#faf8f2}.th-content{display:flex;align-items:center;gap:6px;position:relative}.sermon-table th .sort-button{display:flex;align-items:center;gap:6px;border:0;background:transparent;color:inherit;font:inherit;text-align:left;padding:0;cursor:pointer}.sermon-table th .sort-button:hover{color:#214f88}.sort-indicator{color:#8a8276;font-size:11px}.sort-indicator::after{content:"^v"}.sermon-table th[aria-sort=ascending] .sort-indicator::after{content:"^"}.sermon-table th[aria-sort=descending] .sort-indicator::after{content:"v"}.info-popover{display:inline-flex;align-items:center;position:relative;outline:0}.info-icon{display:inline-grid;place-items:center;width:16px;height:16px;border:1px solid #bbb3a3;border-radius:50%;background:#fff;color:#5e574d;font:700 11px/1 system-ui,sans-serif;cursor:help}.info-popover:hover .info-icon,.info-popover:focus .info-icon{border-color:#214f88;color:#214f88}.info-bubble{display:none;position:absolute;z-index:20;top:calc(100% + 8px);left:0;width:max-content;max-width:280px;min-width:220px;background:#fff;border:1px solid #bdb4a6;border-radius:6px;box-shadow:0 10px 24px rgba(0,0,0,.14);color:#2d2a26;font:12px/1.4 system-ui,sans-serif;padding:10px;white-space:normal;text-transform:none;letter-spacing:0}.info-popover:hover .info-bubble,.info-popover:focus .info-bubble{display:block}.sermon-table th:last-child .info-bubble{left:auto;right:0}.sermon-table td{font-size:15px}.sermon-table a,a{color:#214f88}.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px}.card{display:block;background:#fff;border:1px solid #d9d4c8;border-radius:8px;padding:14px;color:#1d3554;text-decoration:none}.card strong{display:block;font:700 16px/1.2 system-ui,sans-serif}.card span{display:block;color:#6c655b;font:13px/1.4 system-ui,sans-serif;margin-top:8px}.sermon-layout{display:grid;grid-template-columns:minmax(0,1fr) 310px;gap:28px}.article,.infobox{background:#fff;border:1px solid #d9d4c8;border-radius:8px;padding:22px}.infobox{align-self:start;position:sticky;top:24px}.infobox dl{display:grid;grid-template-columns:94px 1fr;gap:8px;margin:0}.infobox dt{font:700 13px system-ui,sans-serif;color:#655d53}.infobox dd{margin:0}.infobox ul{padding-left:18px;overflow-wrap:anywhere}.button{display:inline-block;background:#214f88;color:white;text-decoration:none;border-radius:6px;padding:9px 12px;margin:14px 0;font:700 14px system-ui,sans-serif}.callout{border-left:4px solid #a45f00;background:#fff7e8;padding:12px 14px;margin:18px 0}.callout.note{border-color:#34699a;background:#eef6ff}.callout ul{margin:8px 0 0;padding-left:20px}.pill-row{display:flex;flex-wrap:wrap;gap:8px}.pill{background:#eef1ea;border:1px solid #d4d9ce;border-radius:999px;padding:5px 9px;font:14px system-ui,sans-serif}.transcript{max-width:820px}.transcript p{margin:0 0 1em}.entity-list{display:grid;gap:6px}.entity-row{display:flex;justify-content:space-between;gap:16px;background:#fbfaf6;border:1px solid #e3ded4;border-radius:6px;padding:10px 12px;text-decoration:none;color:#1d3554}.entity-row strong{font-family:system-ui,sans-serif}.muted{color:#746f66}code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:.9em;overflow-wrap:anywhere}@media(max-width:850px){.app-shell{display:block}.sidebar{position:static;height:auto;border-right:0;border-bottom:1px solid #d9d4c8}.content{padding:24px 18px}.sermon-layout{grid-template-columns:1fr}.infobox{position:static}h1{font-size:32px}}""",
    )
    write_text(
        site_dir / "assets" / "site.js",
        """document.querySelectorAll("[data-search-input]").forEach((input)=>{const root=input.closest(".panel")||document;const rows=[...root.querySelectorAll("[data-search-row]")];input.addEventListener("input",()=>{const q=input.value.trim().toLowerCase();rows.forEach((row)=>{row.style.display=!q||row.dataset.search.includes(q)?"":"none";});});});
document.querySelectorAll("[data-sortable]").forEach((table)=>{const tbody=table.tBodies[0];if(!tbody)return;const headers=[...table.tHead.rows[0].cells];const valueFor=(row,index,type)=>{const cell=row.cells[index];const raw=(cell?.dataset.sortValue||cell?.textContent||"").trim();if(type==="number"){const number=Number.parseFloat(raw.replace(/[^0-9.-]/g,""));return Number.isFinite(number)?number:-Infinity;}return raw.toLowerCase();};const sort=(index,dir)=>{const type=headers[index].dataset.sortType||"text";const multiplier=dir==="asc"?1:-1;const rows=[...tbody.rows];rows.sort((a,b)=>{const left=valueFor(a,index,type);const right=valueFor(b,index,type);if(left<right)return -1*multiplier;if(left>right)return 1*multiplier;return 0;});rows.forEach((row)=>tbody.appendChild(row));headers.forEach((header)=>{header.removeAttribute("aria-sort");header.dataset.sortDir="";});headers[index].dataset.sortDir=dir;headers[index].setAttribute("aria-sort",dir==="asc"?"ascending":"descending");};headers.forEach((header,index)=>{const button=header.querySelector("button");if(!button)return;button.addEventListener("click",()=>{const next=header.dataset.sortDir==="asc"?"desc":"asc";sort(index,next);});});const initial=table.dataset.sortInitial;if(initial){const [indexText,dir]=initial.split(":");const index=Number.parseInt(indexText,10);if(Number.isInteger(index)&&headers[index])sort(index,dir==="asc"?"asc":"desc");}});""",
    )


def prefix(depth: int) -> str:
    return "../" * depth


def entity_filename(name: str) -> str:
    return slugify(name) + ".html"


def sort_attr(value: object) -> str:
    return escape(str(value or "").casefold(), quote=True)


def record_key(record: SermonRecord) -> str:
    if record.youtube_id:
        return f"youtube-id:{record.youtube_id}"
    if record.youtube_url:
        return f"youtube-url:{record.youtube_url}"
    return f"{record.date}:{record.title}"


def search_blob(values: list[object]) -> str:
    return escape(" ".join(str(value or "") for value in values).casefold(), quote=True)
